export const UPDATE_BOARD = 'UPDATE_BOARD';
export const UPDATE_SCORE = 'UPDATE_SCORE';
export const UPDATE_GAME_STATUS = 'UPDATE_GAME_STATUS';
export const UPDATE_STEPS_STATUS = 'UPDATE_STEPS_STATUS';
export const NEW_GAME = 'NEW_GAME';
